### ISSUE TITLE
Upgrade unity version to 2020.1.0b10

### ISSUE THREAD

**Issue by RMSteenwijk** [Nexus-Aurora/vr-unity-demo#6]
After talking to several developers we've come to the conclusion to update the unity project to version 2020.1.0b10.

**Comment by RMSteenwijk** [comment]
Naming Conventions:
LWRP: Lightweight rendering pipeline (now URP)
URP: Universal Rendering Pipeline
HDRP: High Definition Rendering Pipeline
SRP: Scriptable Rendering Pipeline
VFX Graphs: Visual Effects Graphs

--------------------

With unity 2019 they have introduced the Scriptable Rendering Pipeline or SRP, which deprecates the built-in rendering pipeline for various reasons. 
* First of all it is a lot more performant as it is made for one purpose and does not need to meet every aspect of every game. A low poly 2d game does not need to know how to render an insanely high quality 3d scene
* It is extensible, as you can change how it works for your specific needs, hence the name Scriptable Rendering Pipeline
* You can create own pipelines or use and/or modify existing ones (URP/LWRP, HDRP)
* Enables the use of new Post Processing Effects, which can not only be applied to a camera but to areas and volumes or whatever else. Take for example a cave, you want it to be dark, hence you add an Effect that makes the camera spooky dark but just in the area of that cave, once left the lighting change (The one you get in real life when you change from dark to light) happens. All of this is doable with SRP
* Enables the use of VFX Graphs. This enables you to create a particle system and effects from a graph which is a topic for itself as it's a huge system just as the next point.
* Shader Graphs. Every game has Shaders and now we can create custom shaders in mere seconds. This can create insane effects in practically no time with little computing expense (depends on complexity of shader)

The question then remains if we want to use the HDRP which will enable us to go all out on fidelity and create a stunning game on the most used platforms like Consoles and PC.
Or use the URP which is optimized for all devices but in the expense of some (minor) quality settings.

Sources:
* https://blogs.unity3d.com/2019/09/20/how-the-lightweight-render-pipeline-is-evolving/
* https://www.youtube.com/watch?v=5MuA92xUJCA
* https://unity.com/srp/universal-render-pipeline

**Comment by brycekahle** [comment]
[`2010.1.0b11`](https://unity3d.com/beta/2020.1b#downloads) has been released. Should we use that?

**Comment by RMSteenwijk** [comment]
@brycekahle No, check the readme of the master branch for the correct version

**Comment by brycekahle** [comment]
@RMSteenwijk I mistyped, that should read `2020.1.0b11` (not 2010), which was released on June 3rd, 2020. It is a patch update of the specified version in the README `2020.1.0b10`, so going from `b10` to `b11`.

**Comment by jorgeparavicini** [comment]
I don't think it's necessary to change every time to the newest Unity version. We will change once the official version has been released, but for now, there is little incentive to do so.

**Comment by DeadlyMagikarps** [comment]
Until a stable release is pushed out. We should stick to only that build during the duration of the entire development. 

If we have a justifiable reason to upgrade to a new version of Unity (on stable release) for a new feature that would be beneficial to the developers, that can be discussed again.

Moving to new version is too risk and there are things that already don't work in 2020 compared to 2019. Almost everything VR and Unity's XR system broke a lot of things, deprecated a lot of older features, and are in beta and preview mode.

My biggest worry is breaking someone else's code (or mine) due to a minor update because Unity decided to rename variables and those references get broken. 

SteamVR and OpenVR are far from perfect and incremental updates breaks more than it fixes. Just my 2 cents.
